nav:
  - Home: index.md
  - Guides:
    - Adapters: guides/adapters.md
    - Specifications: guides/specifications.md
  - Architecture:
    - Overview: architecture/overview.md
    - Records: adr/
  - API Reference: api/api_reference.md
